version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 347059689224.dkr.ecr.us-east-1.amazonaws.com
  
  build:
    commands:
       - mvn -Pproduction package dockerfile:build dockerfile:push
